import * as THREE from 'three';
import {GLTFExporter} from 'three/addons/exporters/GLTFExporter.js';
import {readFile,writeFile} from 'node:fs/promises';
globalThis.FileReader=class{readAsArrayBuffer(blob){blob.arrayBuffer().then(result=>{this.result=result;this.onloadend?.();});}};
const outline=JSON.parse(await readFile(new URL('./reference-hand/logo-outline.json',import.meta.url),'utf8'));
const shape=new THREE.Shape(outline.points.map(p=>new THREE.Vector2(...p))),root=new THREE.Group();root.name='Logo_Unismuh_3D';
const bodyGeo=new THREE.ExtrudeGeometry(shape,{depth:.08,steps:1,bevelEnabled:true,bevelThickness:.006,bevelSize:.004,bevelSegments:2});bodyGeo.translate(0,0,-.04);
const body=new THREE.Mesh(bodyGeo,new THREE.MeshStandardMaterial({name:'Gold_Edge',color:0xd6aa42,metalness:.48,roughness:.3}));body.name='Solid_Gold_Edge';root.add(body);
const frontGeo=new THREE.ShapeGeometry(shape),pos=frontGeo.getAttribute('position'),uv=frontGeo.getAttribute('uv');
for(let i=0;i<pos.count;i++)uv.setXY(i,pos.getX(i)/outline.width+.5,.5-pos.getY(i)/outline.height);
frontGeo.translate(0,0,.047);
const front=new THREE.Mesh(frontGeo,new THREE.MeshBasicMaterial({name:'Original_Logo_Front',color:0xffffff}));front.name='Logo_Front';root.add(front);
const backGeo=new THREE.ShapeGeometry(shape);backGeo.rotateY(Math.PI);backGeo.translate(0,0,-.047);
const back=new THREE.Mesh(backGeo,new THREE.MeshStandardMaterial({name:'Navy_Back',color:0x151877,metalness:.25,roughness:.35}));back.name='Logo_Back';root.add(back);
root.userData={thickness:.092,description:'Extruded Unismuh emblem following the original transparent silhouette',width:outline.width,height:outline.height};
const exported=Buffer.from(await new GLTFExporter().parseAsync(root,{binary:true}));
const jl=exported.readUInt32LE(12),doc=JSON.parse(exported.subarray(20,20+jl)),oldBin=exported.subarray(28+jl),png=await readFile(new URL('../public/images/logo-unismuh.png',import.meta.url));
const payload=Buffer.concat([oldBin,png,Buffer.alloc((4-png.length%4)%4)]);doc.bufferViews.push({buffer:0,byteOffset:oldBin.length,byteLength:png.length});doc.buffers[0].byteLength=payload.length;
doc.images=[{bufferView:doc.bufferViews.length-1,mimeType:'image/png'}];doc.samplers=[{magFilter:9729,minFilter:9987,wrapS:33071,wrapT:33071}];doc.textures=[{sampler:0,source:0}];
const frontMat=doc.materials.find(m=>m.name==='Original_Logo_Front');frontMat.pbrMetallicRoughness.baseColorTexture={index:0};
const json=Buffer.from(JSON.stringify(doc)),jsonChunk=Buffer.concat([json,Buffer.alloc((4-json.length%4)%4,32)]),total=28+jsonChunk.length+payload.length,out=Buffer.alloc(total);
out.writeUInt32LE(0x46546c67,0);out.writeUInt32LE(2,4);out.writeUInt32LE(total,8);out.writeUInt32LE(jsonChunk.length,12);out.writeUInt32LE(0x4e4f534a,16);jsonChunk.copy(out,20);out.writeUInt32LE(payload.length,20+jsonChunk.length);out.writeUInt32LE(0x004e4942,24+jsonChunk.length);payload.copy(out,28+jsonChunk.length);
await writeFile(new URL('../public/intro/logo-unismuh-3d.glb',import.meta.url),out);console.log(`Logo GLB: ${out.length} bytes, silhouette extrusion, embedded PNG, 3 meshes`);
